spring:
  application:
    name: finance-api

  datasource:
     url: jdbc:h2:tcp://localhost/~/easymanage
     driver-class-name: org.h2.Driver
     username: sa
     password:


#  datasource:
#    url: jdbc:mysql://localhost:3306/easymanage
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 5287

  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8083
